[package]
name = "orbuculum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
network = { path = "network" }
server = { version = "0.1.0", path = "server" }
tokio = { version = "1.23.0", features = ["full"] }
udev = "0.7.0"
