on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run script file
      run: |
         cd scripts
         bash build-dev-docker.sh
         cd ..
         docker run --network=host --rm -v '$(pwd):/work' --workdir /work -ti docker.io/ssfdust/orbuculum-dev:latest cargo build
      shell: bash
